### PR TITLE
Add Postings compression project.

### PR DESCRIPTION
**Pull request by krasi-georgiev**
ping @gouthamve if he can add more details and possibly add himself as a mentor.

### CODE REVIEW

**Comment by gouthamve** [comment]
Hold this until I can verify a couple of things

**Comment by krasi-georgiev** [comment]
ping @gouthamve

**Comment by krasi-georgiev** [comment]
ping @gouthamve

**Comment by idvoretskyi** [comment]
@gouthamve @krasi-georgiev any updates on this?

**Comment by krasi-georgiev** [comment]
not on my side, still waiting for @gouthamve to see what he had in mind to add here.

**Comment by brian-brazil** [comment]
:+1:

**Comment by krasi-georgiev** [comment]
@idvoretskyi 	feel free to merge. If @gouthamve 	needs to change anything can open another PR.

**Pull request merged**
