### PR TITLE
prometheus -  Unify the testing across all packages.

### PR DESCRIPTION
**Pull request by krasi-georgiev**

### CODE REVIEW

**Comment by Gouthamve** [comment]
This looks more like a small 1-2 days of work. While this can be picked up people looking to contribute, I'm apprehensive to adding it as full GSoC idea.

**Comment by krasi-georgiev** [comment]
Yes this is a rather short assignment. 
@Gouthamve  What is the general  time frame we need to define something as a task?
I am thinking maybe I can stack some other refactoring to make it a bigger task.

https://github.com/prometheus/prometheus/issues/3647 for example

**Comment by Gouthamve** [comment]
So GSoC would last 3 months and while it could have several tasks, I'd ideally have tasks that are going to take more than 2weeks.

**Comment by krasi-georgiev** [comment]
ok go it.

**Pull request closed without merging**
