### PR TITLE
Add SOC proposal of Virtual Kubelet.

### PR DESCRIPTION
**Pull request by k82cn**
Signed-off-by: Klaus Ma <klaus1982.cn@gmail.com>

### CODE REVIEW

**Comment by k82cn** [comment]
Already submit org application to soc, and CNCF sandbox for Volcano. If we missed deadline of soc, I'll close this PR :)

**Comment by idvoretskyi** [comment]
cc @caniszczyk

**Comment by caniszczyk** [comment]
not a CNCF project atm so we can't accept this

If you want to convince VK to add a project for volcano in its list you can do that

**Comment by idvoretskyi** [comment]
@k82cn any updates?

**Comment by k82cn** [comment]
I'm talking with VK on that, did not get feedback right now :)

**Comment by rbitia** [comment]
We are willing to add Volcano to VK as a provider, and we'd be willing to support this for SOC. 

Thanks!

**Comment by idvoretskyi** [comment]
@rbitia great, thanks for clarifying.

**Pull request merged**
