### PR TITLE
Added a new proposal for GSOC 2020

### PR DESCRIPTION
**Pull request by Abhik1998**
This PR is to merge the proposal for GSOC 2020

### CODE REVIEW

**Comment by Abhik1998** [comment]
Okay sorry, I have added that now.

**Comment by idvoretskyi** [comment]
cc @nikhita

**Comment by nikhita** [comment]
@Abhik1998 Thanks for the PR! For Kubernetes, we require that mentors be members and active contributors to the repo. Membership is required in order to be able to lgtm and approve PRs from mentees.

Unfortunately, it looks like you are not a member of @kubernetes yet. Would you like to edit the proposal to only include @johnsonj as the mentor for now?

**Comment by Abhik1998** [comment]
Yep I have added him.

**Comment by nikhita** [comment]
@Abhik1998 To be clear, we'll need to _only_ list @johnsonj as the mentor right now since they are the only with membership to the @kubernetes GitHub org.

**Comment by Abhik1998** [comment]
Okay I do not have any issue in that.

**Comment by idvoretskyi** [comment]
@Abhik1998 has any prior discussion of this proposal happened somewhere? I see that the issue https://github.com/kubernetes-sigs/cluster-addons/issues/40 has been created just a few hours ago and no further discussion has happened there.

**Comment by Abhik1998** [comment]
Nope there was no prior discussion but separately these issues or features were discussed

**Comment by idvoretskyi** [comment]
@Abhik1998 so can you please link the previous conversation?

**Comment by Abhik1998** [comment]
These are some links where the discussion was carried on 
https://github.com/kubernetes-sigs/cluster-addons/issues/27

**Comment by idvoretskyi** [comment]
Great. @johnsonj please approve.

**Comment by Abhik1998** [comment]
@idvoretskyi

**Comment by idvoretskyi** [comment]
@Abhik1998 merged this by the accident. Can you please submit a proposal with @johnsonj as an only mentor, and we are good to go.

**Comment by Abhik1998** [comment]
Sure @idvoretskyi but this [PR ](https://github.com/cncf/soc/pull/138) mentions of @greenpau as co-mentor so if you approve that then I can add him also

**Pull request merged**
